version: "3.7"

services:

  item-app:
    image: item-app:v1
    ports:
      - 80:8080

    working_dir: /app

    # volumes:
    #   - app-db:/data/db


  item-db:
    image: mongo:3

    volumes:
      - app-db:/data/db


volumes:
  app-db:
